/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://owpj77l63zfm3mktxjyb73czcu.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-sp7td3fmb5aodbgs4cyny7rsti",
    "aws_cognito_identity_pool_id": "us-east-1:91be0e1e-ab3a-40a9-85e9-fdbbbd192cfe",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_r1L0sFrFR",
    "aws_user_pools_web_client_id": "sib2l679237otl9joc7o9k3rp",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
